#ifndef DEFAULTS_H 
#define DEFAULTS_H

#define DEFAULT_HEAP_PATH "/sys/kernel/debug/ion/display"
#define DEFAULT_HEAP_INFO "allocated size"
#define DEFAULT_REPEAT 1
#define DEFAULT_STREAM WIDEVINE_DASH_H264_CLEAR_HD
#define DEFAULT_WAIT 10000
#define DEFAULT_PLAYTIME 15000
#define DEFAULT_PLAY_CLEAR 1
#define DEFAULT_PLAY_SECURE 0
#define DEFAULT_PLAY_UHD 0
#define LEAK_THRESHOLD 0.2

#define MAX_STRING_LENGTH 100
#define MAX_OUTPUT 10

#endif